name = "BlobDetection"
uuid = "b9b9df36-df81-4d1f-9383-9378060e8564"
authors = ["Riccardo Foffi <riccardo.foffi@protonmail.com> and contributors"]
version = "0.0.1"

[deps]
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"

[compat]
ImageFiltering = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
